// ReaderShell.jsx
function ReaderShell({ active, onNav, children }) {
  return (
    <div className="reader">
      <header className="reader__nav">
        <div className="reader__nav-inner">
          <a className="reader__brand" href="#today" onClick={(e)=>{e.preventDefault();onNav("today");}}>
            <svg width="28" height="28" viewBox="0 0 44 44" fill="none">
              <rect x="2" y="2" width="40" height="40" rx="8" fill="#1E1E2E" stroke="#7C6CDC"/>
              <path d="M14 18 L14 26 L18 26" stroke="#D4A574" strokeWidth="1.5" strokeLinecap="round" fill="none"/>
              <circle cx="22" cy="22" r="2.5" fill="#7C6CDC"/>
              <path d="M30 18 L30 26 L26 26" stroke="#D4A574" strokeWidth="1.5" strokeLinecap="round" fill="none"/>
            </svg>
            <div>
              <div className="reader__brand-name">CLAUDE NEWS</div>
              <div className="reader__brand-sub">L L M · W I K I</div>
            </div>
          </a>
          <nav className="reader__navlinks">
            <a href="#today" className={active==="today"?"is-active":""} onClick={(e)=>{e.preventDefault();onNav("today");}}>Today</a>
            <a href="#archive" className={active==="archive"?"is-active":""} onClick={(e)=>{e.preventDefault();onNav("archive");}}>Archive</a>
            <a href="#wiki" className={active==="wiki"?"is-active":""} onClick={(e)=>{e.preventDefault();onNav("wiki");}}>Wiki</a>
            <a href="#about">About</a>
          </nav>
          <button className="reader__search">
            <img src="https://unpkg.com/lucide-static@latest/icons/search.svg" />
            <span>Search…</span>
            <span className="kbd">⌘K</span>
          </button>
        </div>
      </header>
      <main className="reader__main">{children}</main>
      <footer className="reader__footer">
        <span>CLAUDE NEWS · LLM-WIKI</span>
        <span>· auto-generated by Claude Code News Aggregator</span>
        <span>· source: <code>github.com/mandy82477/ObsidianLab</code></span>
      </footer>
    </div>
  );
}
window.ReaderShell = ReaderShell;
